import {
  BarChart3,
  Calendar,
  Receipt,
  BookOpen,
  MapPin,
  Users,
  Calculator,
  Euro,
  TrendingUp,
  MessageSquare,
  CheckSquare,
  Layers,
  Database,
  ClipboardList,
  Mail,
  FileSpreadsheet,
  Send,
  TestTube2,
  Wallet,
  Car,
  Truck,
  Inbox,
  Wrench,
  CalendarClock,
  Factory,
  HardHat,
  Banknote,
} from 'lucide-react';

export interface ToolConfig {
  id: string;
  name: string;
  description: string;
  href: string;
  icon: typeof BarChart3;
  color: string;
}

export const ALL_TOOLS: ToolConfig[] = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    description: 'Unternehmenskennzahlen: Lagerbestände, anstehende Auslieferungen und mehr',
    href: '/dashboard',
    icon: BarChart3,
    color: 'from-indigo-500 to-purple-500',
  },
  {
    id: 'dispo-planung',
    name: 'Dispo-Planung',
    description: 'Planung und Verwaltung von Lieferungen, Routen und Fahrzeugen',
    href: '/dispo-planung',
    icon: Calendar,
    color: 'from-purple-500 to-pink-500',
  },
  {
    id: 'saisonplanung',
    name: 'Kundenliste',
    description: 'Call-Liste, Saisonmengen, Platzbauer-Beziehungen und Preise pflegen',
    href: '/saisonplanung',
    icon: ClipboardList,
    color: 'from-amber-500 to-red-500',
  },
  {
    id: 'projekt-verwaltung',
    name: 'Projekt-Verwaltung',
    description: 'Überblick über alle Projekte von Angebot bis Bezahlung',
    href: '/projekt-verwaltung',
    icon: Layers,
    color: 'from-purple-500 to-indigo-600',
  },
  {
    id: 'platzbauer-verwaltung',
    name: 'Platzbauer-Verwaltung',
    description: 'Platzbauer verwalten mit Vereinen, Saisonprojekten und Nachträgen',
    href: '/platzbauer-verwaltung',
    icon: HardHat,
    color: 'from-amber-500 to-orange-600',
  },
  {
    id: 'kreditoren',
    name: 'Kreditoren-Verwaltung',
    description: 'Verwaltung offener Rechnungen und Kreditoren mit Übersicht und Statistiken',
    href: '/kreditoren',
    icon: Receipt,
    color: 'from-red-600 to-red-800',
  },
  {
    id: 'debitoren',
    name: 'Debitoren-Verwaltung',
    description: 'Offene Forderungen von Vereinen verwalten mit Mahnwesen und Zahlungsverfolgung',
    href: '/debitoren',
    icon: Banknote,
    color: 'from-green-600 to-emerald-700',
  },
  {
    id: 'privat-kreditoren',
    name: 'Private Kreditoren',
    description: 'Private Kreditorenverwaltung für Julian und Luca',
    href: '/privat-kreditoren',
    icon: Wallet,
    color: 'from-purple-500 to-violet-600',
  },
  {
    id: 'wiki',
    name: 'Wiki',
    description: 'Dokumentation, Anleitungen und Wissenssammlung für das Team',
    href: '/wiki',
    icon: BookOpen,
    color: 'from-amber-500 to-orange-600',
  },
  {
    id: 'konkurrenten',
    name: 'Konkurrenten-Karte',
    description: 'Übersicht aller Konkurrenten und Lieferkosten-Analyse nach Postleitzahl',
    href: '/konkurrenten',
    icon: MapPin,
    color: 'from-blue-600 to-indigo-600',
  },
  {
    id: 'kunden-karte',
    name: 'Kunden-Karte',
    description: 'Google Maps-Karte mit allen Kundenstandorten',
    href: '/kunden-karte',
    icon: Users,
    color: 'from-green-600 to-emerald-600',
  },
  {
    id: 'raben-rechner',
    name: 'Raben Rechner',
    description: 'Frachtkostenrechner Raben Spedition mit Live-Dieselpreisen',
    href: '/raben-rechner',
    icon: Truck,
    color: 'from-blue-600 to-indigo-700',
  },
  {
    id: 'speditionskosten',
    name: 'Speditionskosten Rechner',
    description: 'Preisberechnung für Ziegelmehl mit Spedition oder Eigenlieferung',
    href: '/speditionskosten',
    icon: Calculator,
    color: 'from-red-500 to-orange-500',
  },
  {
    id: 'fixkosten',
    name: 'Fixkosten Rechner',
    description: 'Berechnung der Fixkosten für die Ziegelmehl-Herstellung',
    href: '/fixkosten',
    icon: Euro,
    color: 'from-orange-500 to-red-500',
  },
  {
    id: 'variable-kosten',
    name: 'Variable Kosten Rechner',
    description: 'Berechnung der variablen Kosten und Gesamtherstellkosten',
    href: '/variable-kosten',
    icon: TrendingUp,
    color: 'from-blue-500 to-indigo-500',
  },
  {
    id: 'vorschlaege',
    name: 'Verbesserungen',
    description: 'Vorschläge zur Verbesserung des Online-Tools anlegen und verwalten',
    href: '/vorschlaege',
    icon: MessageSquare,
    color: 'from-green-500 to-emerald-500',
  },
  {
    id: 'todos',
    name: 'TODO-Verwaltung',
    description: 'Aufgaben im Kanban-Board verwalten und bearbeiten',
    href: '/todos',
    icon: CheckSquare,
    color: 'from-purple-500 to-violet-500',
  },
  {
    id: 'stammdaten',
    name: 'Stammdaten',
    description: 'Firmendaten, Artikel und zentrale Stammdaten verwalten',
    href: '/stammdaten',
    icon: Database,
    color: 'from-blue-500 to-cyan-600',
  },
  {
    id: 'anfragen',
    name: 'Anfragen',
    description: 'Automatisch erkannte E-Mail-Anfragen verwalten und zu Kunden zuordnen',
    href: '/anfragen',
    icon: Mail,
    color: 'from-teal-500 to-cyan-500',
  },
  {
    id: 'kalender',
    name: 'Kalender',
    description: 'Termine und Ereignisse verwalten mit Monats- und Wochenansicht',
    href: '/kalender',
    icon: Calendar,
    color: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'excel-import',
    name: 'Excel Import',
    description: 'E-Mail-Adressen aus Excel-Dateien extrahieren (Duplikate entfernen)',
    href: '/excel-import',
    icon: FileSpreadsheet,
    color: 'from-green-500 to-emerald-600',
  },
  {
    id: 'newsletter',
    name: 'Newsletter',
    description: 'Newsletter-Empfänger verwalten mit Abmeldelinks und Excel-Import',
    href: '/newsletter',
    icon: Send,
    color: 'from-purple-500 to-indigo-600',
  },
  {
    id: 'qualitaetssicherung',
    name: 'QS-Tool',
    description: 'Siebanalysen nach DIN 18035-5 mit Körnungslinie und PDF-Prüfberichten',
    href: '/qualitaetssicherung',
    icon: TestTube2,
    color: 'from-emerald-500 to-teal-600',
  },
  {
    id: 'fahrtkosten',
    name: 'Fahrtkosten',
    description: 'Kilometer-Erfassung mit Quick-Add für wiederkehrende Strecken',
    href: '/fahrtkosten',
    icon: Car,
    color: 'from-red-500 to-rose-600',
  },
  {
    id: 'logistikpartner',
    name: 'Logistikpartner',
    description: 'Speditionen und Transportpartner mit Fahrzeugen, Liefergebieten und Preisen',
    href: '/logistikpartner',
    icon: Truck,
    color: 'from-blue-500 to-indigo-600',
  },
  {
    id: 'email-dashboard',
    name: 'Email Dashboard',
    description: 'Alle Postfächer live überwachen mit Echtzeit-Updates',
    href: '/email-dashboard',
    icon: Inbox,
    color: 'from-teal-500 to-cyan-600',
  },
  {
    id: 'instandhaltung',
    name: 'Instandhaltung',
    description: 'Tägliche, wöchentliche und monatliche Begehungen der Produktionsanlage',
    href: '/instandhaltung',
    icon: Wrench,
    color: 'from-orange-500 to-red-600',
  },
  {
    id: 'schichtplanung',
    name: 'Schichtplanung',
    description: 'Mitarbeiter-Schichten planen mit Drag & Drop Wochenkalender',
    href: '/schichtplanung',
    icon: CalendarClock,
    color: 'from-violet-500 to-purple-600',
  },
  {
    id: 'produktion',
    name: 'Produktion',
    description: 'Produzierte Tonnen erfassen mit mobilem Swipe-Picker',
    href: '/produktion',
    icon: Factory,
    color: 'from-orange-500 to-amber-600',
  },
];

export const DEFAULT_TOOL_VISIBILITY = ALL_TOOLS.reduce<Record<string, boolean>>((acc, tool) => {
  acc[tool.id] = true;
  return acc;
}, {});
